# monitoring/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'joanna-backend'
    static_configs:
      - targets: ['neilchat-backend:9300']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
