model_list:
  - model_name: ollama-llama3
    litellm_params:
      model: ollama/qwen2.5-coder:7b
      api_base: "http://host.docker.internal:11434"
  - model_name: neilzeneger:latest
    litellm_params:
      model: ollama/neilzeneger:latest
      api_base: "http://host.docker.internal:11434"
  - model_name: qwen-coder
    litellm_params:
      model: ollama/qwen2.5-coder:7b
      api_base: "http://host.docker.internal:11434"

litellm_settings:
  drop_params: True
  set_verbose: True
  disable_spend_logs: True
